"use strict";

const ACTION_CONSTANTS = {
    SET_IMAGES_TO_STATE: "SET_IMAGES_TO_STATE",
    TOGGLE_SHOW_ALL: "TOGGLE_SHOW_ALL",
    TOGGLE_IMAGE_FAV_STATUS: "TOGGLE_IMAGE_FAV_STATUS",
    SET_IMAGES_TO_FAVS: "SET_IMAGES_TO_FAVS",
    ADD_IMAGE_TO_FAVS: "ADD_IMAGE_TO_FAVS",
    REMOVE_IMAGE_FROM_FAVS: "REMOVE_IMAGE_FROM_FAVS"
};

export default ACTION_CONSTANTS;