"use strict";

const ACTION_CONSTANTS = {
    SET_IMAGES_TO_STATE: "SET_IMAGES_TO_STATE",
    TOGGLE_SHOW_ALL: "TOGGLE_SHOW_ALL",
    TOGGLE_IMAGE_FAV_STATUS: "TOGGLE_IMAGE_FAV_STATUS"
};

export default ACTION_CONSTANTS;